apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: min-side-arbeidsgiver
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://arbeidsgiver.labs.nais.io/min-side-arbeidsgiver
  liveness:
    path: /min-side-arbeidsgiver/internal/isAlive
    initialDelay: 20
  readiness:
    path: /min-side-arbeidsgiver/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /min-side-arbeidsgiver/internal/metrics
  vault:
    enabled: false
  webproxy: false
  idporten:
    enabled: false
  envFrom:
    - secret: min-side-ag-frontend
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: API_GATEWAY
      value: http://min-side-arbeidsgiver-api.fager
    - name: LOGIN_URL
      value: https://min-side-ag-fakelogin.labs.nais.io/login?issuer=selvbetjening&sub=123456789&domain=labs.nais.io&redirect=https://arbeidsgiver.labs.nais.io/min-side-arbeidsgiver/
    - name: PROXY_LOG_LEVEL
      value: debug
    - name: BRUKER_API_URL
      value: http://localhost:8081
    - name: GIT_COMMIT
      value: {{commit}}
    - name: ARBEIDSFORHOLD_DOMAIN
      value: https://arbeidsgiver.labs.nais.io
    - name: SYKEFRAVAER_DOMAIN
      value: https://arbeidsgiver.labs.nav.no
  accessPolicy:
    outbound:
      external:
        - host: https://arbeidsgiver.labs.nav.no
      rules:
        - application: min-side-arbeidsgiver-api
        - application: notifikasjon-bruker-api
