on: workflow_dispatch

name: Deploy dev og experimental labs

env:
  IMAGE: ghcr.io/${{ github.repository }}/min-side-arbeidsgiver-api:${{github.sha}}


jobs:
  deploy-dev-manual:
    name: deploy dev manual
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resource: [ nais/dev-gcp.yaml, nais/experimental-labs-gcp.yaml ]

    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - name: "Deploy ${{ matrix.resource }}"
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: ${{ matrix.resource }}
          PRINT_PAYLOAD: true
          VAR: commit=${{ github.sha }}
          REF: ${{ github.sha }}
          IMAGE: ${{ env.IMAGE }}